language: objective-c
os: osx
osx_image: xcode12.2
env:
  - CI_USE_SWIFTPM=true
  - CI_USE_SWIFTPM=false
before_install:
  - gem install xcpretty
  - |
    if ! $CI_USE_SWIFTPM ; then
      carthage update --no-use-binaries --platform ios
    fi
before_script:
  - set -o pipefail
script: |
  PROJECT_ARG=
  if $CI_USE_SWIFTPM ; then
    rm -rf *.xcodeproj
  else
    PROJECT_ARG="-project ./Unio.xcodeproj"
  fi
  xcodebuild test $PROJECT_ARG -scheme Unio -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=13.0,name=iPhone 11' | xcpretty -c
notifications:
  email: false
